### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by Boschgopi** [juspay/hyperswitch-cdk#114]
```
git clone https://github.com/juspay/hyperswitch-cdk.git
cd hyperswitch-cdk
bash install.sh
```

This API will be removed in the next major release. 
⏳  Bootstrapping environment aws://767397921485/us-east-1... 
Trusted accounts for deployment: (none) 
Trusted accounts for lookup: (none) 
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize. 
CDKToolkit: creating CloudFormation changeset... 
❌  Environment aws://767397921485/us-east-1 failed bootstrapping: Error [ValidationError]: Stack:arn:aws:cloudformation:us-east-1:767397921485:stack/CDKToolkit/a4990440-e1f6-11ee-88da-0e853effafe9 is in DELETE_FAILED state and can not be updated. 
    at Request.extractError (/usr/lib/node_modules/aws-cdk/lib/index.js:379:46692) 
    at Request.callListeners (/usr/lib/node_modules/aws-cdk/lib/index.js:379:91437) 
    at Request.emit (/usr/lib/node_modules/aws-cdk/lib/index.js:379:90885) 
    at Request.emit (/usr/lib/node_modules/aws-cdk/lib/index.js:379:199281) 
    at Request.transition (/usr/lib/node_modules/aws-cdk/lib/index.js:379:192833) 
    at AcceptorStateMachine.runTo (/usr/lib/node_modules/aws-cdk/lib/index.js:379:157705) 
    at /usr/lib/node_modules/aws-cdk/lib/index.js:379:158035 
    at Request.<anonymous> (/usr/lib/node_modules/aws-cdk/lib/index.js:379:193125) 
    at Request.<anonymous> (/usr/lib/node_modules/aws-cdk/lib/index.js:379:199356) 
    at Request.callListeners (/usr/lib/node_modules/aws-cdk/lib/index.js:379:91605) { 
  code: 'ValidationError', 
  time: 2024-03-15T06:46:20.524Z, 
  requestId: 'ed28bb08-98da-4797-8468-a960a885026d', 
  statusCode: 400, 
  retryable: false, 
  retryDelay: 686.9833624271799 
} 
Stack:arn:aws:cloudformation:us-east-1:767397921485:stack/CDKToolkit/a4990440-e1f6-11ee-88da-0e853effafe9 is in DELETE_FAILED state and can not be updated. 
An error occurred (NoSuchBucket) when calling the ListObjectVersions operation: The specified bucket does not exist 
An error occurred (NoSuchBucket) when calling the ListObjectVersions operation: The specified bucket does not exist 
An error occurred (InvalidClientTokenId) when calling the ListAttachedRolePolicies operation: The security token included in the request is invalid

**Comment by nitesh-balla** [comment]
Hi @Boschgopi, It seems that the CDK toolkit is currently in a DELETE_FAILED state. To resolve this, kindly navigate to the AWS console -> CloudFormation and manually delete the CDKToolkit stack. It should transition to a DELETED state before redeploying the stack.

**Comment by Boschgopi** [comment]
already,we did the same thing but still getting error,

**Comment by nitesh-balla** [comment]
By same error, do you mean the CDK Toolkit is going to DELETE_FAILED state when you try to delete it? If CDK Toolkit is deleted, this error shouldn't occur. The error clearly states that CDK Toolkit is in DELETE_FAILED state. Could you try to deploy the stack in a different region or please try to delete the CDK toolkit again?

**Comment by Boschgopi** [comment]
Hi @nitesh-balla As you indicated, I attempted to deployed a stack in a different region,  and deleted the CDKtoolkit again, and run the commands.
 I continue to see the same issue.
 CREATE_FAILED        | AWS::IAM::Role          | LookupRole

The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: c1010f85-1819-470d-93c6-4d28d88c9390; Proxy: null

)



5:51:52 pm | CREATE_FAILED        | AWS::IAM::Role          | CloudFormationExecutionRole

Resource handler returned message: "The security token included in the request is invalid (Service: Iam, Status Code: 403, Request ID: ce3d7f11-4cd5-4f28-9b57-08129f3543f5)" (RequestToken: d97fa2a9-e35e-

7539-d580-f18e1898f6d9, HandlerErrorCode: AccessDenied)



5:51:52 pm | CREATE_FAILED        | AWS::IAM::Role          | ImagePublishingRole

Resource handler returned message: "The security token included in the request is invalid (Service: Iam, Status Code: 403, Request ID: a756579c-2418-4d9b-8946-2c8a243fc57f)" (RequestToken: 10efed5b-9aab-

ce54-2902-9ec762ade856, HandlerErrorCode: AccessDenied)



5:51:52 pm | CREATE_FAILED        | AWS::IAM::Role          | FilePublishingRole

Resource handler returned message: "The security token included in the request is invalid (Service: Iam, Status Code: 403, Request ID: e2d55976-04f0-4c3a-a48f-d60590715f30)" (RequestToken: 4d622a9a-ecbc-

ef6e-a98c-a8eeb018048c, HandlerErrorCode: AccessDenied)



5:51:55 pm | DELETE_FAILED        | AWS::IAM::Role          | CloudFormationExecutionRole

Resource handler returned message: "The security token included in the request is invalid (Service: Iam, Status Code: 403, Request ID: ebf39d27-9e91-4684-b545-630621ac687e)" (RequestToken: 8a2cde81-ee86-

ae64-5bfd-d53e14e26800, HandlerErrorCode: AccessDenied)



5:51:55 pm | DELETE_FAILED        | AWS::IAM::Role          | ImagePublishingRole

Resource handler returned message: "The security token included in the request is invalid (Service: Iam, Status Code: 403, Request ID: 33c34876-c52d-457f-b67b-eb4d0172baca)" (RequestToken: e44aa453-bcd6-

54c1-b7c0-4dfd1f5b4f6f, HandlerErrorCode: AccessDenied)



5:51:55 pm | DELETE_FAILED        | AWS::IAM::Role          | FilePublishingRole

Resource handler returned message: "The security token included in the request is invalid (Service: Iam, Status Code: 403, Request ID: 02d91a72-f217-4fe2-b65e-45f53f67e506)" (RequestToken: 76680fdf-193b-

1700-91c2-a7579445c6ce, HandlerErrorCode: AccessDenied)



 ❌  Environment aws://767397921485/us-west-1 failed bootstrapping: Error: The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_FAILED (The following resource(s) failed to delete: [ImagePublishingRole, FilePublishingRole, CloudFormationExecutionRole]. )

    at FullCloudFormationDeployment.monitorDeployment (/usr/lib/node_modules/aws-cdk/lib/index.js:430:10615)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async /usr/lib/node_modules/aws-cdk/lib/index.js:435:2329

    at async Promise.all (index 0)

    at async CdkToolkit.bootstrap (/usr/lib/node_modules/aws-cdk/lib/index.js:435:2174)

    at async exec4 (/usr/lib/node_modules/aws-cdk/lib/index.js:488:54378)



The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_FAILED (The following resource(s) failed to delete: [ImagePublishingRole, FilePublishingRole, CloudFormationExecutionRole]. )

**Comment by nitesh-balla** [comment]
@Boschgopi The error that's posted previously and this is different. Last time, it was CDK Toolkit being in DELETE_FAILED state and CDK was unable to create a new CDKToolkit because it is already in DELETE_FAILED state. Now, This error occurred while creating the CDKToolkit. From the error message, I guess the reason might be that the user who is trying to deploy the stack might not have IAM CreatePolicy access. Is this an organizational account that you are using? Few organizations restrict their user accounts from having IAM Permissions. Could you please check if your organization allows you to create IAM policies?

**Comment by Boschgopi** [comment]
Hi @nitesh-balla we are using personal account and gave administrator access


Trusted accounts for deployment: (none)

Trusted accounts for lookup: (none)

Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.

CDKToolkit: creating CloudFormation changeset...

11:23:40 am | CREATE_FAILED        | AWS::IAM::Role          | LookupRole

The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 393621db-19f0-40c4-9824-e5e7dc94976f; Proxy: null

)



11:23:45 am | DELETE_FAILED        | AWS::IAM::Role          | CloudFormationExecutionRole

Resource handler returned message: "The security token included in the request is invalid (Service: Iam, Status Code: 403, Request ID: 11daeb24-8eae-4282-8748-b7481d205d74)" (RequestToken: ca525c87-b22a-

a41a-35af-5d45a30f4942, HandlerErrorCode: AccessDenied)

**Comment by nitesh-balla** [comment]
@Boschgopi Did you export all the below environment variables in your terminal? It seems like your permission issue. 
`AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, `AWS_SESSION_TOKEN `.

**Comment by Boschgopi** [comment]
yes we did the export those AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN .

**Comment by nitesh-balla** [comment]
Could you please do aws sts get-caller-identity and let me know if you are able to see your account details, the credentials might be expired. Can you please join this [Slack Channel](https://hyperswitch-io.slack.com/join/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) and post your queries in the #dev-support channel there?
