### ISSUE TITLE
[FEATURE] Create separate node groups for monitoring, locker , control center, istio and other services.

### ISSUE THREAD

**Issue by nitesh-balla** [juspay/hyperswitch-cdk#128]
In-order to achieve a similar setup to our production, we need to segregate Kubernetes resources into appropriate node groups, with predefined instance class, size, and desired number of instances, etc.

Related Issues: 
- [ ] [On demand Node Group for locker](https://github.com/juspay/hyperswitch-cdk/issues/67)

**Comment by prasunna09** [comment]
#136 closes this issue
