### ISSUE TITLE
Adding assertions for validating permissions before starting

### ISSUE THREAD

**Issue by shakthi-22** [juspay/hyperswitch-cdk#58]
The goal is to check upfront if the user running the CDK script has the required permissions for various AWS services. If not, the script should call out the necessary permissions required and prompt the user to enable them before proceeding further

**Comment by nitesh-balla** [comment]
The updated CDK installation script now includes several enhanced features for improved user experience and security:

1. Credential Validation: The script now checks and confirms if the user's credentials are current or have the necessary permissions.
2. Region Confirmation: It identifies the user's existing AWS region and seeks consent to proceed or offers the option to deploy in a different region.
3. Region Code Validation: The script validates the specified region code and will continuously prompt the user until a valid region is entered.
4. Regional Deployment Permissions: There's an assessment to ensure the user has the required permissions for deploying Hyperswitch in the chosen region.
5. Access Policy Assessment: It evaluates the access policy permissions necessary for deploying Hyperswitch services.
6. Root User Detection: The script identifies if the user is operating as a root user and advises against it for security reasons.
7. Cross-Platform Support: Seamless execution and installation of dependencies are now supported for both Linux and macOS users.
8. Tool Installation: The script supports the installation of `kubectl` and `awscli`, tailored to the user's architecture.
9. Password and API Key Validation: It now checks if the database passwords and admin API keys entered by the user are strong and adhere to the required conventions.
