### ISSUE TITLE
Ensure the CDK script returns success component wise

### ISSUE THREAD

**Issue by shakthi-22** [juspay/hyperswitch-cdk#77]
The CDK script should not fail for all components just because of one. Even if one fails, other components should execute successfully and the error in that one component should be called out. On rerunning the script only the component that failed should be installed again

**Comment by nitesh-balla** [comment]
We might not be able to achieve this because AWS Cloud Development Kit generates CloudFormation template during compile time, not runtime. Therefore, it lacks the ability to dynamically adjust the deployment based on runtime errors.
